name: SleepyUtilities
version: 1.0.0
main: live.amsleepy.sleepyutilities.SleepyUtilities
api-version: '1.17'
author: sleepy

commands:
  sleepyutilities:
    description: Manage the SleepyUtilities plugin
    usage: /<command> <reload|status|toggle|antiredstoneclock>
    permission: sleepyutilities.manage
    permission-message: You do not have permission to use this command.
    aliases: [su]

permissions:
  sleepyutilities.manage:
    description: Allows the player to manage the plugin
    default: op
  sleepyutilities.reload:
    description: Allows the player to reload the plugin
    default: op
  sleepyutilities.status:
    description: Allows the player to view the status of the plugin features
    default: op
  sleepyutilities.toggle:
    description: Allows the player to enable or disable plugin features
    default: op
  sleepyutilities.antiredstoneclock:
    description: Allows the player to manage the anti-redstone clock feature
    default: op
  sleepyutilities.lockchunk:
    description: Allows the player to lock the current chunk
    default: op
  sleepyutilities.unlockchunk:
    description: Allows the player to unlock the current chunk
    default: op